#!/bin/bash

name="DL for HTT mass reconstruction"

echo "Installing $name..."

# find where this repository is placed by getting this file's directory
instal_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

bin_dir=$instal_dir/Delphes/Delphes-3.4.2/
# check if this seems to be already installed, in this case do nothing
if [[ $PATH = *$bin_dir* ]] || [[ $(grep -l "$name" ~/.bashrc) = ~/.bashrc ]]
then
    echo 'It seems like you already have installed this!'
    echo 'Not changing anything.'
else
    if [[ $instal_dir = $HOME* ]]
    then
        instal_dir=~${instal_dir#$HOME}
    fi
    # add the bashrc extension corresponding to this repository to your own bashrc
    echo "" >> ~/.bashrc
    echo "# --- add $name ---" >> ~/.bashrc
    echo ". $instal_dir/bashrc_ext" >> ~/.bashrc
    echo "Installation completed."
fi
