#!/bin/bash

mkdir -p /data2/${USER}/ML/HTT_analysis_FastSim_NanoAOD
cd /data2/${USER}/ML/HTT_analysis_FastSim_NanoAOD

for d in $(ls /data2/${USER}/ML/HTT_analysis_FastSim_NanoAOD | grep -ve ALL)
do
    cd /data2/${USER}/ML/HTT_analysis_FastSim_NanoAOD/$d
    txt_merger -o Htt_merged_NanoAODSIM_${d}.txt $(ls | grep Htt_.*_NanoAODSIM_${d}.txt | grep -ve Htt_merged_)
    rm Htt_[0-9]*_NanoAODSIM_${d}.txt
    txt_to_hdf5 Htt_merged_NanoAODSIM_${d}.txt Htt_merged_NanoAODSIM_${d}
done

cd /data2/${USER}/ML/HTT_analysis_FastSim_NanoAOD
mkdir -p ALL
cd ALL
txt_merger -o Htt_merged_NanoAODSIM_ALL.txt $(find /data2/${USER}/ML/HTT_analysis_FastSim_NanoAOD/ -type f -name Htt_merged_NanoAODSIM_\*.txt)
txt_to_hdf5 Htt_merged_NanoAODSIM_ALL.txt Htt_merged_NanoAODSIM_ALL
find . -type f -name Htt_merged_NanoAODSIM_.*.txt -delete
