#!/bin/bash

mkdir -p /data2/ltorterotot/ML/FastSim_NanoAOD_to_NN
cd /data2/ltorterotot/ML/FastSim_NanoAOD_to_NN

find . -type f -iname \*.txt -delete
find . -type f -iname \*.h5 -delete
find . -type f -iname Htt_merged_\* -delete

rsync -au --progress torterotot@lyoserv.in2p3.fr:/gridgroup/cms/htt/shared_files/Data/NanoAODSIM/nevents_* /data2/ltorterotot/ML/FastSim_NanoAOD_to_NN/

for d in $(ls /data2/ltorterotot/ML/FastSim_NanoAOD_to_NN | grep -ve ALL)
do
    cd /data2/ltorterotot/ML/FastSim_NanoAOD_to_NN/$d

    for f in $(ls | grep Htt_.*_NanoAODSIM.root)
    do
        (
            ln -s  $f ${f%.*}_${d}.root
            HTT_FastSim_NanoAOD_tree_analysis ${f%.*}_${d}.root ${f%.*}_${d}
            # rm $f
        ) &
    done
    wait
done
