inputs = [
    "tau1_pt_gen",
    "tau1_eta_gen",
    "tau1_phi_gen",
    "tau2_pt_gen",
    "tau2_eta_gen",
    "tau2_phi_gen",
    # "jet1_pt_gen",
    # "jet1_eta_gen",
    # "jet1_phi_gen",
    # "jet2_pt_gen",
    # "jet2_eta_gen",
    # "jet2_phi_gen",
    # "remaining_jets_pt_gen",
    # "remaining_jets_eta_gen",
    # "remaining_jets_phi_gen",
    # "remaining_jets_N_gen",
    "MET_pt_gen",
    "MET_phi_gen",
    # "MET_covXX_gen",
    # "MET_covXY_gen",
    # "MET_covYY_gen",
    # "MET_significance_gen",
    "mT1_gen",
    "mT2_gen",
    "mTtt_gen",
    "mTtot_gen",
    # "PU_npvsGood_gen",
    ]
