inputs = [
    "leg1_pt_gen",
    "leg1_eta_gen",
    "leg1_phi_gen",
    "leg2_pt_gen",
    "leg2_eta_gen",
    "leg2_phi_gen",
    # "jet1_pt_gen",
    # "jet1_eta_gen",
    # "jet1_phi_gen",
    # "jet2_pt_gen",
    # "jet2_eta_gen",
    # "jet2_phi_gen",
    # "remaining_jets_pt_gen",
    # "remaining_jets_eta_gen",
    # "remaining_jets_phi_gen",
    # "remaining_jets_N_gen",
    "MET_pt_reco",
    "MET_phi_reco",
    # "MET_covXX_gen",
    # "MET_covXY_gen",
    # "MET_covYY_gen",
    # "MET_significance_gen",
    "mT1_leg_gen",
    "mT2_leg_gen",
    "mTtt_leg_gen",
    "mTtot_leg_gen",
    # "PU_npvsGood_gen",
    ]
